server:
  port: ${APP_PORT:8080}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:barcodes}
    username: ${DB_USERNAME:barcodes}
    password: ${DB_PASSWORD:barcodes}
  liquibase:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:barcodes}
    user: ${DB_USERNAME:barcodes}
    password: ${DB_PASSWORD:barcodes}
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
