server:
  port: ${APP_PORT:8080}

spring:
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:./data/barcodes
    driverClassName: org.h2.Driver
    username: barcodes
    password: barcodes
  liquibase:
    url: jdbc:h2:file:./data/barcodes
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
